# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVMDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks

  # Pods for MVVMDemo
#  use_frameworks!
pod 'ReactiveCocoa','~>2.1.8'
end
